services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "443:5678"  # HTTPS access
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - DB_SQLITE_POOL_SIZE=1
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ~/.n8n:/home/node/.n8n
      - ./wait-for-ngrok.sh:/app/wait-for-ngrok.sh
    depends_on:
      - ngrok
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-ngrok.sh && n8n start"]

  ngrok:
    image: ngrok/ngrok:latest
    command: http n8n:5678 --log=stdout
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
